import type { Service } from './types'

export const services: Service[] = [
  {
    id: 'brand-strategy',
    title: 'Brand Strategy',
    subtitle: 'Strategic Foundation',
    description:
      'We define the strategic backbone of your brand — positioning, narrative, audience architecture, and competitive differentiation. Every decision is rooted in research and crafted for long-term relevance.',
    image: 'https://picsum.photos/seed/brand-strategy/800/600',
    seed: 'brand-strategy',
    features: [
      'Brand positioning & architecture',
      'Audience segmentation & mapping',
      'Competitive landscape analysis',
      'Brand narrative & messaging',
      'Tone of voice guidelines',
      'Go-to-market strategy',
    ],
    process: ['Discovery & Audit', 'Strategic Framework', 'Narrative Development', 'Validation & Refinement'],
    stats: [
      { label: 'Projects Delivered', value: '120+' },
      { label: 'Avg. Engagement Lift', value: '64%' },
      { label: 'Client Retention', value: '94%' },
    ],
    cta: { text: 'Discuss Your Strategy', href: 'mailto:hello@kairos.studio' },
    delivery: '4–6 weeks',
    testimonial: {
      text: 'They didn\'t just define our strategy — they redefined how we see ourselves. The clarity we gained was transformative.',
      author: 'Marta Chen',
      role: 'CEO, Lumina Group',
    },
  },
  {
    id: 'visual-identity',
    title: 'Visual Identity',
    subtitle: 'Brand Expression',
    description:
      'From logotypes to comprehensive design systems, we craft visual languages that communicate your brand at every touchpoint. Distinctive, coherent, and built to scale.',
    image: 'https://picsum.photos/seed/visual-identity/800/600',
    seed: 'visual-identity',
    features: [
      'Logo & mark design',
      'Color system & typography',
      'Brand guidelines',
      'Stationery & collateral',
      'Brand pattern library',
      'Iconography system',
    ],
    process: ['Visual Exploration', 'Concept Development', 'System Design', 'Guidelines Documentation'],
    stats: [
      { label: 'Identity Systems', value: '80+' },
      { label: 'Avg. Brand Recall', value: '72%' },
      { label: 'Design Awards', value: '18' },
    ],
    cta: { text: 'Request Portfolio', href: 'mailto:hello@kairos.studio' },
    delivery: '6–10 weeks',
    testimonial: {
      text: 'The visual system they created feels like it was always meant to be. Every detail, every colour — intentional and beautiful.',
      author: 'James Okonkwo',
      role: 'Founder, Studio CIRCA',
    },
  },
  {
    id: 'art-direction',
    title: 'Art Direction',
    subtitle: 'Visual Storytelling',
    description:
      'We lead the visual narrative for campaigns, editorials, and brand content. From concept to execution, every frame is composed with intent and cinematic precision.',
    image: 'https://picsum.photos/seed/art-direction/800/600',
    seed: 'art-direction',
    features: [
      'Campaign concept & mood boards',
      'Photography & video direction',
      'Set design & styling',
      'Visual narrative architecture',
      'Post-production oversight',
      'Campaign asset creation',
    ],
    process: ['Creative Briefing', 'Visual Research', 'Production Direction', 'Post-Production'],
    stats: [
      { label: 'Campaigns Produced', value: '200+' },
      { label: 'Editorial Features', value: '45+' },
      { label: 'Avg. Engagement', value: '3.2x' },
    ],
    cta: { text: 'View Case Studies', href: 'mailto:hello@kairos.studio' },
    delivery: '2–8 weeks (varies)',
    testimonial: {
      text: 'Their art direction brought our campaign to life in ways we couldn\'t have imagined. Every frame was a piece of art.',
      author: 'Sofia Reyes',
      role: 'Marketing Director, Bellaterra',
    },
  },
  {
    id: 'motion-design',
    title: 'Motion Design',
    subtitle: 'Moving Visuals',
    description:
      'We create motion that communicates — animated identities, explainer sequences, typographic animation, and immersive visual storytelling for digital and broadcast.',
    image: 'https://picsum.photos/seed/motion-design/800/600',
    seed: 'motion-design',
    features: [
      'Brand motion systems',
      'Explainer & product videos',
      'Typography animation',
      'Title sequences',
      'Social media content',
      'Interactive prototypes',
    ],
    process: ['Storyboard & Styleframes', 'Animation', 'Sound Design', 'Delivery & Optimization'],
    stats: [
      { label: 'Projects Animated', value: '150+' },
      { label: 'Avg. View Duration', value: '2.8x' },
      { label: 'Platform Reach', value: '12M+' },
    ],
    cta: { text: 'See Our Reel', href: 'mailto:hello@kairos.studio' },
    delivery: '3–8 weeks',
    testimonial: {
      text: 'The motion identity they built for us became instantly recognisable. It elevated our entire brand perception.',
      author: 'Lars Nilsson',
      role: 'Brand Director, NORD',
    },
  },
  {
    id: 'editorial-design',
    title: 'Editorial Design',
    subtitle: 'Print & Publishing',
    description:
      'We design publications, books, magazines, and reports that demand to be picked up. Page architecture, typographic systems, and tactile material choices that elevate content.',
    image: 'https://picsum.photos/seed/editorial-design/800/600',
    seed: 'editorial-design',
    features: [
      'Magazine & book design',
      'Annual report design',
      'Typography & grid systems',
      'Information design',
      'Print production management',
      'Digital publishing',
    ],
    process: ['Content Architecture', 'Grid & Typography', 'Layout Design', 'Print Supervision'],
    stats: [
      { label: 'Publications', value: '65+' },
      { label: 'Pages Designed', value: '4,200+' },
      { label: 'Awards Nominated', value: '12' },
    ],
    cta: { text: 'Browse Publications', href: 'mailto:hello@kairos.studio' },
    delivery: '4–12 weeks',
    testimonial: {
      text: 'They transformed our annual report into something people actually wanted to keep on their coffee tables. Extraordinary craft.',
      author: 'Priya Sharma',
      role: 'Communications Lead, Ethos Capital',
    },
  },
  {
    id: 'digital-design',
    title: 'Digital Design',
    subtitle: 'Interactive Experiences',
    description:
      'We craft digital products, websites, and interactive experiences that balance beauty with function. Motion-rich interfaces, thoughtful micro-interactions, and seamless user journeys.',
    image: 'https://picsum.photos/seed/digital-design/800/600',
    seed: 'digital-design',
    features: [
      'Website & product design',
      'UI/UX strategy & prototyping',
      'Design system development',
      'Micro-interaction design',
      'Responsive & adaptive layout',
      'Front-end consultancy',
    ],
    process: ['User Research', 'Wireframes & Prototypes', 'Visual Design', 'Handoff & Support'],
    stats: [
      { label: 'Digital Products', value: '90+' },
      { label: 'Avg. Conversion Lift', value: '45%' },
      { label: 'Users Reached', value: '8M+' },
    ],
    cta: { text: 'Start Your Project', href: 'mailto:hello@kairos.studio' },
    delivery: '6–14 weeks',
    testimonial: {
      text: 'The site they designed for us loads beautifully, feels effortless, and has measurably improved our conversion rate. Truly world-class.',
      author: 'David Kim',
      role: 'CEO, Form & Function',
    },
  },
]
